name: .NET 8 CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore and Build
        run: |
          dotnet restore ./Server/GestaoDeEstacionamento.sln
          dotnet build ./Server/GestaoDeEstacionamento.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run all tests
        run: |
          dotnet restore ./Server/GestaoDeEstacionamento.sln
          dotnet test ./Server/GestaoDeEstacionamento.sln --configuration Release --no-restore --verbosity normal
